
// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_es.js
// Copyright (c) 2011 Tableau Software, Incorporated and its licensors. All rights reserved.
// Protected by U.S. Patent 7,089,266; Patents Pending.
// 
// Portions of the code
// Copyright (c) 2002 The Board of Trustees of the Leland Stanford Junior University. All rights reserved.
// ---------------------------------------------------------------------------------------------------------------------

(function(w) {
  var s = {
    AreYouSureCancel: "Cancelar",
    AreYouSureDelete: "Eliminar",
    AreYouSureText: "¿Está seguro?",
    AuthAddData: "Añadir datos",
    AuthAutoRecoveredSessionMessage: "Se han recuperado las modificaciones iniciales hechas en el libro de trabajo durante la sesión. Haga clic en Guardar o Guardar como para registrar las modificaciones. Haga clic en Revertir para abrir el libro de trabajo guardado.",
    AuthAutoSavedRecoveredMessage: "Se recuperaron automáticamente las ediciones anteriores. Use Revertir para volver al libro de trabajo como se guardó. (Desde autoguardado. Revertir no se implementó.)",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "Columnas",
    AuthCardTitleFilters: "Filtros",
    AuthCardTitleMarks: "Marcas",
    AuthCardTitleMeasureValues: "Valores de medidas",
    AuthCardTitlePages: "Páginas",
    AuthCardTitleRows: "Filas",
    AuthColorPaletteAutomatic: "Automático",
    AuthColorTransparencyLabel: "Transparencia:",
    AuthDashboardPaneBlankZone: "En blanco",
    AuthDashboardPaneHorizontalZone: "Horizontal",
    AuthDashboardPaneSheets: "Hojas",
    AuthDashboardPaneSize: "Tamaño",
    AuthDashboardPaneVerticalZone: "Vertical",
    AuthDashboardPaneZoneObjects: "Objetos",
    AuthFontFamilyAndSize: "{0} {1}",
    AuthIncludeTotalsLabel: "Incluir totales",
    AuthLeftPaneLabelDashboard: "Dashboard",
    AuthLeftPaneTabLabelAnalytics: "Análisis",
    AuthMarkSizeLabel: "Tamaño de marca:",
    AuthMarksCardChooseField: "Más campos",
    AuthMarksCardEncodingTooltipBasic: "Arrastre las dimensiones o medidas aquí",
    AuthMarksCardEncodingTooltipOptions: "Arrastre las dimensiones o medidas aquí o haga clic para ver más opciones.",
    AuthMastheadDone: "Fin",
    AuthMastheadDone_Confirm_CanLogin: "¿Desea guardar los cambios al libro de trabajo? <br><br>Deberá iniciar sesión antes de que pueda finalizar el guardado de los cambios.",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "Iniciar sesión y guardar",
    AuthMastheadDone_Confirm_CanLogin_Deny: "No guardar",
    AuthMastheadDone_Confirm_CanSave: "¿Desea guardar los cambios al libro de trabajo?",
    AuthMastheadDone_Confirm_CanSaveAs: "¿Desea guardar los cambios en un nuevo libro de trabajo?",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "Guardar una copia",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "No guardar",
    AuthMastheadDone_Confirm_CanSave_Confirm: "Guardar",
    AuthMastheadDone_Confirm_CanSave_Deny: "No guardar",
    AuthMastheadDone_Confirm_Title: "Guardar el libro de trabajo",
    AuthMastheadHelp: "Ayuda",
    AuthMastheadLogin: "Inicio de sesión",
    AuthMastheadLogout: "Cerrar sesión",
    AuthMastheadRevert: "Revertir",
    AuthMastheadSave: "Guardar",
    AuthMastheadSaveAs: "Guardar como",
    AuthMastheadUserPrefs: "Preferencias del usuario",
    AuthOffLabel: "Desactivado",
    AuthOnLabel: "Activado",
    AuthPillRemove: "Eliminar",
    AuthRenameSheet: "Cambiar nombre de la hoja",
    AuthRenameSheetError: "Cambie el nombre de la hoja por un nombre único",
    AuthResetTooltip: "Restablecer descripción emergente",
    AuthReverseColorLabel: "Inverso",
    AuthSaveButtonCancel: "Cancelar",
    AuthSaveButtonSave: "Guardar",
    AuthSaveConfirmOverwrite: "{0}¿Desea sobrescribirlo?",
    AuthSaveErrorTitle: "Error al guardar",
    AuthSaveLabelEmbedPassword: "Incrustar información de inicio de sesión de fuente de datos",
    AuthSaveLabelName: "Nombre:",
    AuthSaveLabelProject: "Proyecto:",
    AuthSaveLabelShowTabs: "Mostrar hojas como pestañas",
    AuthSaveTitle: "Guardar el libro de trabajo",
    AuthSaveWorkbookSavedMessage: "Libro de trabajo guardado",
    AuthSchemaViewerHeaderData: "Datos",
    AuthSchemaViewerHeaderDimensions: "Dimensiones",
    AuthSchemaViewerHeaderMeaures: "Medidas",
    AuthSchemaViewerHeaderParameters: "Parámetros",
    AuthSchemaViewerHeaderSets: "Conjuntos",
    AuthShowMeApply: "Aplicar",
    AuthShowMeCantApply: "No se puede aplicar",
    AuthSteppedColorLabel: "Pasos:",
    AuthStepsLabel: "pasos",
    AuthToolbarAddAllSubtotals: "Agregar todos los subtotales",
    AuthToolbarCellSize: "Tamaño de celda",
    AuthToolbarCellSizeBigger: "Más grande",
    AuthToolbarCellSizeNarrower: "Más estrecho",
    AuthToolbarCellSizeShorter: "Más corto",
    AuthToolbarCellSizeSmaller: "Más pequeño",
    AuthToolbarCellSizeTaller: "Más alto",
    AuthToolbarCellSizeWider: "Más ancho",
    AuthToolbarCellTypeSquare: "Cuadrado",
    AuthToolbarCellTypeText: "Texto",
    AuthToolbarExport: "Descargar",
    AuthToolbarFont: "Fuente",
    AuthToolbarFontDecrease: "Disminuir tamaño de fuente",
    AuthToolbarFontIncrease: "Aumentar tamaño de fuente",
    AuthToolbarFormatWorkbook: "Formatear libro de trabajo",
    AuthToolbarMarkHideLabels: "Ocultar etiquetas",
    AuthToolbarMarkShowLabels: "Mostrar etiquetas",
    AuthToolbarPauseUpdates: "Detener las actualizaciones",
    AuthToolbarRedo: "Volver a hacer ",
    AuthToolbarRemoveAllSubtotals: "Eliminar todos los subtotales",
    AuthToolbarResumeUpdates: "Reanudar actualizaciones",
    AuthToolbarShare: "Compartir",
    AuthToolbarShowColumnGrandTotals: "Mostrar totales generales de fila",
    AuthToolbarShowMe: "Mostrarme",
    AuthToolbarShowRowGrandTotals: "Mostrar totales generales de columna",
    AuthToolbarSubscribe: "Suscribir",
    AuthToolbarSwap: "Intercambiar",
    AuthToolbarTotals: "Totales",
    AuthToolbarUndo: "Deshacer ",
    AuthToolbarWorksheet: "Hoja de trabajo",
    AuthToolbarZoomLevel: "Cuadrar",
    AuthWorkbookFormatPaneCloseTooltip: "Cerrar el panel de formato",
    AuthWorkbookFormatPaneTitle: "Formatear libro de trabajo",
    AuthenticationRequired: "Se requiere autenticación",
    AuthorBylineText: "Ver más de este autor",
    AutomaticDashboardSizeText: "Se modificará el tamaño del dashboard para ajustarse a cualquier pantalla en la que se muestre",
    BaseClientAllAxisRanges: "Todos los intervalos de eje",
    BaseClientAllChanges: "Todos los cambios",
    BaseClientAllFilters: "Todos los filtros",
    BaseClientAllSorts: "Todos los órdenes",
    BaseClientColumns: "Columnas",
    BaseClientInvalidSheet: "No se puede mostrar la vista para la hoja \'{0}\'. La hoja no es válida.",
    BaseClientRows: "Filas",
    BaseClientSessionExpiredDialogMessage: "El visor ha expirado. Debe actualizar el navegador.",
    BaseClientSessionExpiredDialogTitle: "La sesión expiró",
    BrowserErrorProcessing: "Error de procesamiento del navegador",
    BrowserErrorProcessingMessage: "Ocurrió un error al procesar la respuesta del servidor.",
    CalcEditorAffectedSheets: "Hojas afectadas",
    CalcEditorApply: "Aplicar",
    CalcEditorApplyTooltip: "Aplicar(Ctrl+Intro)",
    CalcEditorApplyTooltipMac: "Aplicar(Cmd+Intro)",
    CalcEditorCalcError: "El cálculo contiene errores.",
    CalcEditorCalcOk: "El cálculo es válido.",
    CalcEditorDependenciesPrefix: "Los cambios hechos en este cálculo pueden modificar lo siguiente:",
    CalcEditorOkButtonTooltip: "Aplicar y cerrar",
    ClearAllButtonText: "Borrar lista",
    CollapseSchemaPane: "Haga clic para reducir",
    ConfirmationButtonConfirm: "Sí",
    ConfirmationButtonDeny: "No",
    ConfirmationTitle: "Confirmar",
    CurrentPagePanelShowHistory: "Mostrar historial",
    CustomViewsAddYourOwnCustomView: "Agregar su propia vista personalizada",
    CustomViewsCancel: "Cancelar",
    CustomViewsCannotChangeDefault: "No se puede cambiar el valor predeterminado de una vista personalizada que no aparece en la lista",
    CustomViewsChangeDefaultTo: "Cambiar el valor predeterminado \"{0}\"",
    CustomViewsCurrentDefaultIs: "El valor predeterminado actual es \"{0}\"",
    CustomViewsDone: "Fin",
    CustomViewsManageCustomViews: "Administrar vistas personalizadas",
    CustomViewsManageHeader: "Anunciar, cambiar nombre y eliminar mis vistas personalizadas",
    CustomViewsMyCustomViews: "Mis vistas personalizadas",
    CustomViewsNameYourCustomView: "Dar nombre a su vista personalizada",
    CustomViewsOriginalName: "Nombre original: \"{0}\"",
    CustomViewsOriginalView: "Vista original",
    CustomViewsOtherCustomViews: "Otras vistas personalizadas",
    CustomViewsRemember: "Recordar",
    CustomViewsRememberMyChanges: "Recordar mis cambios",
    CustomViewsSelectCustomView: "Seleccionar vista personalizada",
    CustomViewsStartManage: "Administrar vistas personalizadas",
    CustomViewsUndo: "Deshacer ",
    CustomViewsUnlistedCustomView: "Vista seleccionada que no aparece en la lista",
    DashboardAuthoringCustomSizeName: "Personalizado",
    DashboardAuthoringHeightSpinnerLabel: "Altura",
    DashboardAuthoringMaximumSizeLabel: "Máximo",
    DashboardAuthoringMinimumSizeLabel: "Mínimo",
    DashboardAuthoringWidthSpinnerLabel: "Anchura",
    DataSourceGenericErrorButtonLabel: "Vuelva a intentarlo",
    DataSourceGenericErrorMsg: "Se ha producido un error al conectar la fuente de datos.",
    DataSourceGenericErrorSubMsg: "Si continúa teniendo problemas, póngase en contacto con su administrador.",
    DialogButtonCancel: "Cancelar",
    DialogButtonDownload: "Descargar",
    DialogButtonExport: "Descargar",
    DialogButtonOK: "Aceptar",
    DialogNoButtonText: "No",
    DialogYesButtonText: "Sí",
    EmptyDashboardMessage: "Agregue hojas aquí",
    EmptyDashboardSubMessage: "Arrastre y suelte o haga doble clic desde la lista que se encuentra a la izquierda.",
    ExpandSchemaPane: "Haga clic para expandir",
    ExportCrosstabDialogMessage: "Se ha generado la tabulación cruzada.",
    ExportCrosstabDialogTitle: "Descargar tabulación cruzada",
    ExportDataDialogMessage: "Se han generado los datos.",
    ExportDataDialogTitle: "Descargar datos",
    ExportImageDialogMessage: "Se ha generado la imagen.",
    ExportImageDialogTitle: "Descargar imagen",
    FunctionTypeAggregate: "Agregación",
    FunctionTypeAll: "Todos",
    FunctionTypeClearTooltip: "Borrar",
    FunctionTypeDate: "Fecha",
    FunctionTypeLogical: "Lógico",
    FunctionTypeNumber: "Número",
    FunctionTypeSearchHint: "Introduzca el texto que desee buscar",
    FunctionTypeString: "Cadena",
    FunctionTypeTableCalculation: "Cálculo de tablas",
    FunctionTypeType: "Tipo",
    FunctionTypeUser: "Usuario",
    GlassPaneLoading: "Cargando...",
    GlassPaneSessionExpired: "La sesión expiró",
    GlassPaneUpdating: "Actualizando...",
    GoToSheet: "Ir a la hoja",
    GotoMyLocationPermissionDeniedError: "Tableau no tiene permiso para usar su ubicación. Compruebe la configuración de la ubicación e inténtelo de nuevo.",
    GotoMyLocationPositionUnavailableError: "Tableau no encuentra su ubicación. compruebe la conexión a internet e inténtelo de nuevo.",
    GotoMyLocationTimeoutError: "Nuestro intento para encontrar su ubicación ha agotado el tiempo de espera.",
    GotoMyLocationTooltip: "Ir a mi ubicación",
    HelpMenuItemAllHelpTopics: "Abrir Ayuda Instalada",
    HelpMenuItemContactSupport: "Comuníquese con soporte",
    HelpMenuItemGetHelpAndSupport: "Obtener ayuda y soporte",
    HelpMenuItemWebAuthor1: "Quién puede editar y crear libros de trabajo",
    HelpMenuItemWebAuthor2: "Editar y crear vistas",
    HelpMenuItemWebAuthor3: "Crear un nuevo libro de trabajo y una vista",
    LegendPanelHighlightSelectedItems: "Resaltar los elementos seleccionados",
    LinePatternNone: "Ninguno",
    LogOnButton: "Inicie sesión para continuar",
    ManageCustomViewsDisabledExplanation: "No hay ninguna vista personalizada para gestionar.",
    MapsSearchViewInitialText: "Buscar en mapa",
    MenuBackButton: "Volver",
    MobileClientTapToInteract: "Pulse para interactuar",
    PanZoomSelectToolsLassoSelectionTooltip: "Lazo (D)",
    PanZoomSelectToolsPanTooltip: "Panoramizar (Mayús+Arrastrar)",
    PanZoomSelectToolsRadialSelectionTooltip: "Radial (S)",
    PanZoomSelectToolsRectangularSelectionTooltip: "Rectángulo (A)",
    PanZoomSelectToolsZoomAreaTooltip: "Área de zoom (Ctrl+Mayús+Arrastrar)",
    PanZoomSelectToolsZoomAreaTooltipMac: "Área de zoom (Cmd+Mayús+Arrastrar)",
    PanZoomSelectToolsZoomHomeTooltip: "Zoom en Inicio",
    PanZoomSelectToolsZoomInTooltip: "Aumentar (Doble clic)",
    PanZoomSelectToolsZoomOutTooltip: "Reducir (Mayús+Doble clic)",
    PdfDialogContentDashboard: "Este dashboard",
    PdfDialogContentDashboardSheets: "Hojas en el dashboard",
    PdfDialogContentStory: "Esta historia",
    PdfDialogContentTopSheets: "Hojas en libro de trabajo",
    PdfDialogContentWorksheet: "Esta hoja",
    PdfDialogImageSize: "Tamaño de imagen (px)",
    PdfDialogPaperSize: "Tamaño de papel",
    PdfDialogScalingLabel: "Escala",
    PdfDialogSectionContent: "Contenido",
    PdfDialogSectionLayout: "Trazado",
    PdfDialogSelectSheetToChangePrintScaling: "Hojas para descargar",
    PdfDialogThumbnailPageSizeLabel: "Tamaño de página",
    PdfDialogThumbnailScalingLabel: "Escala:",
    PdfExportFitHigh: "Como mucho {0} de alto",
    PdfExportFitOneHigh: "Como mucho 1 página de alto",
    PdfExportFitOneWide: "Como mucho 1 página de ancho",
    PdfExportFitTwoHigh: "Como mucho 2 páginas de alto",
    PdfExportFitTwoWide: "Como mucho 2 páginas de ancho",
    PdfExportFitWide: "Como mucho {0} página de ancho",
    PdfExportFitWideByHigh: "Como mucho {0}x{1}",
    PdfExportMessageError: "Error al producir PDF.",
    PdfExportMessageErrorPng: "Error al descargar PNG",
    PdfExportMessageExporting: "Procesando...",
    PdfExportMessageSettings: "Obteniendo configuración PDF del servidor-",
    PdfExportMessageSettingsError: "Error: No se pudo obtener la configuración de PDF del servidor.",
    PdfExportPageOrientationLandscape: "Horizontal",
    PdfExportPageOrientationPortrait: "Vertical",
    PdfExportPageOrientationPrinter: "Impresora",
    PdfExportPageScaleAuto: "Automático",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "Ejecutivo",
    PdfExportPageSizeFolio: "Folio",
    PdfExportPageSizeLedger: "Libro de contabilidad",
    PdfExportPageSizeLegal: "Legal",
    PdfExportPageSizeLetter: "Carta",
    PdfExportPageSizeNote: "Nota",
    PdfExportPageSizeQuarto: "Cuarto",
    PdfExportPageSizeStatement: "Extracto",
    PdfExportPageSizeTabloid: "Tabloide",
    PdfExportPageSizeUnspecified: "No especificado",
    PdfExportTitlePDF: "Descargar PDF",
    PdfExportTitlePNG: "Descargar PNG",
    PressBackButtonMessage: "Use el botón para volver a una vista válida.",
    PrintPdfDialogContentRequired: "Seleccione al menos una hoja para descargar.",
    PrintPdfDialogMessage: "Se ha generado el archivo PDF.",
    PrintPdfDialogTitle: "Descargar PDF",
    QuickFilterAll: "(Todos)",
    QuickFilterAllValues: "Todos los valores",
    QuickFilterApply: "Aplicar",
    QuickFilterCancel: "Cancelar",
    QuickFilterConditionalsCondition: "Condición",
    QuickFilterConditionalsLimit: "Límite",
    QuickFilterDomainShowFewerValues: "Mostrar menos valores",
    QuickFilterDomainShowMoreValues: "Mostrar más valores",
    QuickFilterExclusive: "Exclusivo",
    QuickFilterInclusive: "Inclusivo",
    QuickFilterMultiSelect: "Múltiple",
    QuickFilterMultipleValues: "(Valores múltiples)",
    QuickFilterNoItems: "Sin elementos.",
    QuickFilterNonNullValues: "Valores no nulos",
    QuickFilterNone: "(Ninguno)",
    QuickFilterOnlyNullValues: "Solo valores nulos",
    QuickFilterSearch: "Buscar",
    QuickFilterSearchAddItemCtrlEnter: "Agregar elemento (Ctrl+Intro)",
    QuickFilterSearchAddItemEnter: "Agregar elemento (Intro)",
    QuickFilterSearchCancel: "Cancelar búsqueda",
    QuickFilterSearchClearTooltip: "Borrar (Esc)",
    QuickFilterSearchCloseTooltip: "Cerrar (Esc)",
    QuickFilterSearchDataIsCaseSensitive: "Los datos son sensibles a mayúsculas.",
    QuickFilterSearchHint: "Escriba el texto para buscar",
    QuickFilterSearchInvalidDataMemberSingular: "\"{0}\" no es un miembro válido del filtro.",
    QuickFilterSearchInvalidDataMembersDialogTitle: "Miembros de datos no válidos",
    QuickFilterSearchInvalidDataMembersPlural: "Los siguientes valores no son miembros válidos del filtro:",
    QuickFilterSearchNoMatches: "Sin coincidencias.",
    QuickFilterSearchResultsNotShownPlural: "{0} no se muestran los resultados",
    QuickFilterSearchResultsNotShownSingular: "No se muestra 1 resultado",
    QuickFilterSearchResultsNotShownZero: "No se muestra resultados",
    QuickFilterSearchTooltip: "Buscar (Intro)",
    QuickFilterShowLargerRange: "Mostrar intervalo más grande",
    QuickFilterShowSmallerRange: "Mostrar intervalo más pequeño",
    QuickFilterSingleSelect: "Individual",
    QuickFilterTitleBarExclusive: "{0} (Exclusivo)",
    QuickFilterUnknown: "<desconocido>",
    QuickFilterValuesInRange: "Valores en intervalo",
    QuickFilterValuesInRangeOrNull: "Valores en intervalo o nulos",
    RefLineEditorInputTitle: "Valor:",
    RelDateAnchored_curr_day: "Día fijado",
    RelDateAnchored_curr_hour: "Hora fijada",
    RelDateAnchored_curr_minute: "Minuto fijado",
    RelDateAnchored_curr_month: "Mes fijado",
    RelDateAnchored_curr_quarter: "Trimestre fijado",
    RelDateAnchored_curr_second: "Segundo fijado",
    RelDateAnchored_curr_week: "Semana fijada",
    RelDateAnchored_curr_year: "Año fijado",
    RelDateAnchored_last_day: "Ayer",
    RelDateAnchored_last_hour: "Hora anterior",
    RelDateAnchored_last_minute: "Minuto anterior",
    RelDateAnchored_last_month: "Mes anterior",
    RelDateAnchored_last_quarter: "Trimestre anterior",
    RelDateAnchored_last_second: "Segundo anterior",
    RelDateAnchored_last_week: "Semana anterior",
    RelDateAnchored_last_year: "Año anterior",
    RelDateAnchored_lastn_day: "Últimos % días",
    RelDateAnchored_lastn_hour: "Últimas % horas",
    RelDateAnchored_lastn_minute: "Últimos % minutos",
    RelDateAnchored_lastn_month: "Últimos % meses",
    RelDateAnchored_lastn_quarter: "Últimos % trimestres",
    RelDateAnchored_lastn_second: "Últimos % segundos",
    RelDateAnchored_lastn_week: "Últimas % semanas",
    RelDateAnchored_lastn_year: "Últimos % años",
    RelDateAnchored_next_day: "Mañana",
    RelDateAnchored_next_hour: "Siguiente hora",
    RelDateAnchored_next_minute: "Siguiente minuto",
    RelDateAnchored_next_month: "Siguiente mes",
    RelDateAnchored_next_quarter: "Siguiente trimestre",
    RelDateAnchored_next_second: "Siguiente segundo",
    RelDateAnchored_next_week: "Siguiente semana",
    RelDateAnchored_next_year: "Siguiente año",
    RelDateAnchored_nextn_day: "Siguientes % días",
    RelDateAnchored_nextn_hour: "Siguientes % horas",
    RelDateAnchored_nextn_minute: "Siguientes % minutos",
    RelDateAnchored_nextn_month: "Siguientes % meses",
    RelDateAnchored_nextn_quarter: "Siguientes % trimestres",
    RelDateAnchored_nextn_second: "Siguientes % segundos",
    RelDateAnchored_nextn_week: "Siguientes % semanas",
    RelDateAnchored_nextn_year: "Siguientes % años",
    RelDateAnchored_todate_day: "Día hasta momento fijado",
    RelDateAnchored_todate_hour: "Hora hasta momento fijado",
    RelDateAnchored_todate_minute: "Minuto hasta momento fijado",
    RelDateAnchored_todate_month: "Mes hasta momento fijado",
    RelDateAnchored_todate_quarter: "Trimestre hasta momento fijado",
    RelDateAnchored_todate_second: "Segundo hasta momento fijado",
    RelDateAnchored_todate_week: "Semana hasta momento fijado",
    RelDateAnchored_todate_year: "Año hasta momento fijado",
    RelDateFilterDays: "Días",
    RelDateFilterHours: "Horas",
    RelDateFilterMinutes: "Minutos",
    RelDateFilterMonths: "Meses",
    RelDateFilterPreview: "{0} a {1}",
    RelDateFilterQuarters: "Trimestres",
    RelDateFilterWeeks: "Semanas",
    RelDateFilterYears: "Años",
    RelDatePickerFiveYears: "5 años",
    RelDatePickerFiveYearsAbbrev: "5a",
    RelDatePickerOneDay: "1 día",
    RelDatePickerOneDayAbbrev: "1d",
    RelDatePickerOneMonth: "1 mes",
    RelDatePickerOneMonthAbbrev: "1m",
    RelDatePickerOneWeek: "1 semana",
    RelDatePickerOneWeekAbbrev: "1s",
    RelDatePickerOneYear: "1 año",
    RelDatePickerOneYearAbbrev: "1a",
    RelDatePickerThreeMonths: "3 meses",
    RelDatePickerThreeMonthsAbbrev: "3m",
    RelDate_curr_day: "Hoy",
    RelDate_curr_hour: "Esta hora",
    RelDate_curr_minute: "Este minuto",
    RelDate_curr_month: "Este mes",
    RelDate_curr_quarter: "Este trimestre",
    RelDate_curr_second: "Este segundo",
    RelDate_curr_week: "Esta semana",
    RelDate_curr_year: "Este año",
    RelDate_last_day: "Ayer",
    RelDate_last_hour: "Hora anterior",
    RelDate_last_minute: "Minuto anterior",
    RelDate_last_month: "Mes anterior",
    RelDate_last_quarter: "Trimestre anterior",
    RelDate_last_second: "Segundo anterior",
    RelDate_last_week: "Semana anterior",
    RelDate_last_year: "Año anterior",
    RelDate_lastn_day: "Últimos % días",
    RelDate_lastn_hour: "Últimas % horas",
    RelDate_lastn_minute: "Últimos % minutos",
    RelDate_lastn_month: "Últimos % meses",
    RelDate_lastn_quarter: "Últimos % trimestres",
    RelDate_lastn_second: "Últimos % segundos",
    RelDate_lastn_week: "Últimas % semanas",
    RelDate_lastn_year: "Últimos % años",
    RelDate_next_day: "Mañana",
    RelDate_next_hour: "Siguiente hora",
    RelDate_next_minute: "Siguiente minuto",
    RelDate_next_month: "Siguiente mes",
    RelDate_next_quarter: "Siguiente trimestre",
    RelDate_next_second: "Siguiente segundo",
    RelDate_next_week: "Siguiente semana",
    RelDate_next_year: "Siguiente año",
    RelDate_nextn_day: "Siguientes % días",
    RelDate_nextn_hour: "Siguientes % horas",
    RelDate_nextn_minute: "Siguientes % minutos",
    RelDate_nextn_month: "Siguientes % meses",
    RelDate_nextn_quarter: "Siguientes % trimestres",
    RelDate_nextn_second: "Siguientes % segundos",
    RelDate_nextn_week: "Siguientes % semanas",
    RelDate_nextn_year: "Siguientes % años",
    RelDate_todate_day: "Día hasta fecha",
    RelDate_todate_hour: "Hora hasta fecha",
    RelDate_todate_minute: "Minuto hasta fecha",
    RelDate_todate_month: "Mes hasta fecha",
    RelDate_todate_quarter: "Trimestre hasta momento fijado",
    RelDate_todate_second: "Segundo hasta fecha",
    RelDate_todate_week: "Semana hasta fecha",
    RelDate_todate_year: "Año hasta fecha",
    RequestAbortedByBrowser: "Solicitud abortada por el navegador",
    SaveIncompleteWorkbookWarning: "No todas las vistas se compartieron cuando se publicó este libro de trabajo. Al guardar el libro de trabajo se sobrescribirá el libro de trabajo original y las vistas no compartidas se perderán. Considere el uso de Guardar como.",
    SaveNoPublishedSheetsBody: "Un libro de trabajo debe tener al menos una hoja publicada para poder guardarse. Haga clic con el botón derecho en una pestaña para publicar una hoja.",
    SaveNoPublishedSheetsTitle: "No es posible guardar",
    SecurityBlockedURLActionHeader: "URL bloqueada",
    SecurityBlockedURLActionMessage: "Se ha bloqueado una URL potencialmente insegura.",
    SelectText: "Seleccionar",
    SelectionToolsLockTooltip: "Pulsar Mayús para bloquear",
    ServerErrorGeneral: "Ocurrió un error al comunicarse con el servidor ({0}).<br>Esto puede ser una condición temporal de la red.  Reintente la operación.<br>Si la situación persiste, comuníquese con su administrador de sistema.",
    ServerErrorInvalidJSON: "Ocurrió un error al comunicarse con el servidor (Invalid JSON).",
    ServerErrorRejected: "Solicitud rechazada por el servidor",
    ServerErrorRejectedMessage: "El servidor no pudo responder debido a una solicitud malformada.<br>Esto puede ser una condición temporal de la red.  Reintente la operación.<br>Si la situación persiste, comuníquese con su administrador de sistema.",
    ServerErrorTitle: "Error de servidor",
    ServerErrorUnexpected: "Error inesperado del servidor",
    SessionEndedAlertMessage: "¿Desea restablecer la vista?",
    SessionEndedAlertTitle: "Sesión terminada por servidor",
    SessionForbiddenActionMsg: "No está autorizado para realizar esta acción.",
    SessionForbiddenActionTitle: "Acción prohibida",
    SessionUnknownErrorTitle: "Error de servidor desconocido",
    ShareDialogAndroidLinkText: "Pulse el icono para abrir el enlace",
    ShareDialogDisplayOptions: "Mostrar opciones",
    ShareDialogDoneButton: "Fin",
    ShareDialogEmail: "Correo electrónico:",
    ShareDialogEmailHelp: "Copiar y pegar enlace en el mensaje de correo electrónico",
    ShareDialogEmbed: "Incrustar:",
    ShareDialogEmbedCodeTableauText: "Obtener información sobre Tableau",
    ShareDialogEmbedHelp: "Copiar y pegar código HTML para incrustar la vista en el sitio web",
    ShareDialogEnterUriForBlogEntry: "Escriba la URL para la entrada de blog",
    ShareDialogEnterValueBetween: "Escriba un valor entre {0} y {1}",
    ShareDialogHeight: "Altura:",
    ShareDialogInvalidHeight: "Altura no válida.",
    ShareDialogInvalidWidth: "Anchura no válida.",
    ShareDialogLink: "Enlace:",
    ShareDialogMobileEmailText: "Pulse el ícono para enviar el enlace por correo electrónico",
    ShareDialogMobileLinkText: "Mantenga pulsado el icono para acceder a otras opciones de compartición",
    ShareDialogPleaseEnterIntegerBetween: "Escriba número entero entre {0} y {1}",
    ShareDialogShowTabs: "Mostrar tabulaciones",
    ShareDialogShowToolbar: "Mostrar barra de herramientas",
    ShareDialogTitle: "Compartir vista",
    ShareDialogUrlForRssLinks: "URL para enlaces RSS:",
    ShareDialogWaitingEmbedMessage: "creando su código incrustado personalizado ...",
    ShareDialogWaitingLinkMessage: "creando su enlace personalizado ...",
    ShareDialogWidth: "Anchura:",
    SignOutFailedMessage: "Error al cerrar sesión. Vuelva a intentarlo.",
    SizeLegendTextMarkSwatch: "Abc",
    SpecialAll: "Todos",
    SpecialError: "#Error",
    SpecialManyValues: "*",
    SpecialMissing: "#Faltante",
    SpecialNoAccess: "#Sin acceso",
    SpecialRagged: "#Irregular",
    SpecialSkipped: "#Omitido",
    SpecialWildcard: "Comodín",
    StopUsingAsLinkingField: "Dejar de usar {0} como campo vinculante",
    StoryPointRevertTooltip: "Revertir",
    SubscribeButtonTooltip: "Suscribir",
    SubscribeCancel: "Cancelar",
    SubscribeContent: "Contenido:",
    SubscribeEnterAddress: "Para recibir suscripciones escriba su dirección de correo electrónico.",
    SubscribeFailure: "Error de suscripción.",
    SubscribeInvalidAddress: "Escriba una dirección de correo electrónico válida. ",
    SubscribeNext: "Siguiente",
    SubscribeSheet: "Esta hoja",
    SubscribeSubject: "Asunto:",
    SubscribeSubscribe: "Suscribir",
    SubscribeSuccess: "La suscripción se guardó correctamente.",
    SubscribeTitle: "Suscribir",
    SubscribeTo: "Para:",
    SubscribeWorkbook: "Hojas en libro de trabajo",
    SumOf: "SUMA de ",
    TableCalcAddSecondary: "Agregar cálculo secundario",
    TableCalcAtTheLevel: "A nivel",
    TableCalcComputeCompoundedRate: "Calcular velocidad compuesta",
    TableCalcComputeTotalAcrossPages: "Calcular total en todas las páginas",
    TableCalcComputeUsing: "Calcular usando",
    TableCalcDialogTitle: "Cálculo de tablas",
    TableCalcPrimaryTitle: "Primario",
    TableCalcRestartingEvery: "Reiniciando cada",
    TableCalcSecondaryTitle: "Secundario",
    TableCalcSortAscending: "Ascendente",
    TableCalcSortAutomatic: "Orden automático",
    TableCalcSortCustom: "Personalizado",
    TableCalcSortDescending: "Descendente",
    TableCalcSpecificDimensions: "Dimensiones específicas",
    TableCalcVisualStructure: "Estructura visual",
    TableCalcWindowCurrentValue: "Valor actual",
    TableCalcWindowNullSetting: "Nulo si no hay valores suficientes",
    TimeLimitExceededTitle: "Límite de tiempo de sesión sobrepasado",
    TimeLimitExceededWarning: "El cálculo de la visualización actual ha sobrepasado el límite de tiempo de sesión.",
    ToolbarAboutTableau: "Acerca de Tableau",
    ToolbarCurrentView: "Vista actual",
    ToolbarCustomViewsDefault: "(Predeterminado)",
    ToolbarCustomViewsDeleteButtonTooltip: "Eliminar esta vista",
    ToolbarCustomViewsEmptyPlaceholder: "Aún no hay nada guardado",
    ToolbarCustomViewsEnterManageButtonText: "Administrar",
    ToolbarCustomViewsErrorChangingPublicPrivateState: "Se ha producido un error al actualizar el estado público/privado en la vista personalizada.",
    ToolbarCustomViewsErrorDeleting: "Se ha producido un error al eliminar la vista personalizada.",
    ToolbarCustomViewsErrorInvalidName: "Introduzca un nombre de vista personalizada válido.",
    ToolbarCustomViewsErrorRenaming: "Se ha producido un error al cambiar el nombre de la vista personalizada.",
    ToolbarCustomViewsErrorSettingDefault: "Se ha producido un error al definir la vista personalizada predeterminada.",
    ToolbarCustomViewsExitManageButtonText: "Fin",
    ToolbarCustomViewsHideViewButtonTooltipWhenPrivate: "Esta vista es privada",
    ToolbarCustomViewsHideViewButtonTooltipWhenPublic: "Esta vista es pública",
    ToolbarCustomViewsMakeItMyDefault: "Establecer como valor predeterminado",
    ToolbarCustomViewsMyViews: "Mis vistas",
    ToolbarCustomViewsOriginalView: "Vista original",
    ToolbarCustomViewsOtherViews: "Otras vistas",
    ToolbarCustomViewsRenameButtonTooltip: "Cambiar nombre de esta vista",
    ToolbarCustomViewsRenameUIClearButtonTooltip: "Cancelar",
    ToolbarCustomViewsRenameUIPlaceholderText: "Cambie nombre de esta vista",
    ToolbarCustomViewsSave: "Guardar",
    ToolbarCustomViewsSaveAreaFillerTextManage: "Administrar",
    ToolbarCustomViewsSaveAreaFillerTextSelect: "Seleccionar vista personalizada",
    ToolbarCustomViewsSaveButtonDisabledTitle: "Escriba un nombre para la vista personalizada en el campo de texto.",
    ToolbarCustomViewsSetDefaultButtonTooltip: "Definir esta vista como predeterminada",
    ToolbarCustomViewsSetDefaultButtonTooltipWhenCurrent: "Esta es su opción predeterminada",
    ToolbarCustomViewsShareItWithOthers: "Definir como pública",
    ToolbarCustomViewsViewNamePlaceholder: "Asigne un nombre a esta vista",
    ToolbarDisabledCrosstabDownloadExplanation: "La tabulación cruzada no está disponible para la descarga.",
    ToolbarDisabledDataDownloadExplanation: "Los datos no están disponibles para la descarga.",
    ToolbarDisabledDownloadExplanation: "Haga clic en la vista para habilitar la descarga de datos y tabulaciones cruzadas",
    ToolbarDisabledWorkbookDownloadExplanation: "Se necesitan permisos para descargar la hoja de trabajo.",
    ToolbarDownload: "Descargar",
    ToolbarEdit: "Editar",
    ToolbarEmbedTitle: "Código de incrustación",
    ToolbarExport: "Descargar",
    ToolbarExportCrosstab: "Tabulación cruzada",
    ToolbarExportData: "Datos",
    ToolbarExportImage: "Imagen",
    ToolbarMoreByAuthor: "más de este autor",
    ToolbarOriginalView: "Vista original",
    ToolbarPauseAutomaticUpdates: "Detener las actualizaciones automáticas",
    ToolbarPrintToPdf: "PDF",
    ToolbarPublicAvailablePlatforms: "Disponible para {0} y {1}",
    ToolbarPublicDownloadLabelMobile: "Más información",
    ToolbarPublicDownloadLabelWeb: "Obtener la aplicación",
    ToolbarPublicExplanationText: "Cree gráficos interactivos, mapas, dashboards y aplicaciones. Publíquelos en cualquier sitio web. Está al alcance de todos y, además, es gratis.",
    ToolbarPublicExplanationTitle: "¿Qué es Tableau Public?",
    ToolbarRefreshData: "Actualizar datos para esta vista",
    ToolbarResumeAutomaticUpdates: "Reanudar las actualizaciones automáticas",
    ToolbarRevertAll: "Deshacer todo",
    ToolbarSendTitle: "Enlace",
    ToolbarSetCurrentPage: "Configurar la página actual",
    ToolbarShare: "Compartir",
    ToolbarShowPerformanceRecording: "Rendimiento",
    ToolbarSubscribeAllView: "Todas las vistas",
    ToolbarSubscribeEmailPlaceholder: "Su correo electrónico",
    ToolbarSubscribeSchedule: "Programa",
    ToolbarSubscribeSubjectPlaceholder: "Línea de asunto",
    ToolbarSubscribeSubmitButton: "Suscribir",
    ToolbarSubscribeSubmitDisabledTitle: "Asegúrese de tener un programa, una dirección de correo electrónico y un asunto válidos para suscribirse.",
    ToolbarSubscribeThisView: "Esta vista",
    ToolbarToggleAutoUpdate: "Alternar actualizaciones automáticas",
    ToolbarViewCount: "{0} vistas",
    ToolbarWorkbook: "Libro de trabajo de Tableau",
    TooltipPanZoomMessage: "Doble clic para zoom / mantener pulsado para hacer paneo",
    UbertipClearSelection: "Borrar<br/>selección",
    UbertipCommand1Mobile: "Borrar<br/>selección",
    UbertipCommand7Mobile: "Ver datos",
    UbertipDrillDownMobile: "Examinar arriba",
    UbertipDrillUpMobile: "Examinar abajo",
    UbertipExcludeMobile: "Excluir",
    UbertipItemsSelected: "elementos seleccionados",
    UbertipKeepOnlyMobile: "Conservar solo esto",
    UbertipMergeMobile: "Agrupar miembros",
    UbertipSortAscendingMobile: "Orden ascendente",
    UbertipSortDescendingMobile: "Orden descendente",
    UbertipSplitMobile: "Desagrupar miembros",
    UbertipViewData: "Ver datos",
    UnhandledExceptionMessage: "Ocurrió un error inesperado. Si continúa recibiendo este error, comuníquese con el administrador de Tableau Server.<br><br>{0}",
    UnhandledExceptionTitle: "Error inesperado",
    UseAsLinkingField: "Usar {0} como campo vinculante",
    VizObjectTypeReferenceLine: "Línea de referencia",
    WindowTableCalcNextValuesLabel: "Valores siguientes",
    WindowTableCalcPreviousValuesLabel: "Valores anteriores"
};

  window.tab = window.tab || {};
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k], placeHolder, i, len;
              for (i = 0, len = arguments.length; i < len; i++) {
                placeHolder = "{" + i + "}";
                formattedString = formattedString.replace(placeHolder, arguments[i]); 
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));


